// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6avm55l5IH6kXGWGxwmCLeU0lA_FPuGM',
    appId: '1:943291471858:web:645ba7556474365c293d6b',
    messagingSenderId: '943291471858',
    projectId: 'hometrain-4e25a',
    authDomain: 'hometrain-4e25a.firebaseapp.com',
    storageBucket: 'hometrain-4e25a.appspot.com',
    measurementId: 'G-DPWV10GN9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs62M-UkNyCUeHukqCHU_ELRv39Vf2gOI',
    appId: '1:943291471858:android:7cfa799002060605293d6b',
    messagingSenderId: '943291471858',
    projectId: 'hometrain-4e25a',
    storageBucket: 'hometrain-4e25a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIEVRNiDosplDkshrK_WJRuOl1UtL4DVc',
    appId: '1:943291471858:ios:fd1266326ff6a728293d6b',
    messagingSenderId: '943291471858',
    projectId: 'hometrain-4e25a',
    storageBucket: 'hometrain-4e25a.appspot.com',
    androidClientId: '943291471858-05rhd8l6htl9tauie1ve8mnu6ccttuha.apps.googleusercontent.com',
    iosClientId: '943291471858-3e37v632sq52itaf1fgofktv27r94365.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeTrain',
  );
}
